### ISSUE TITLE
typecasting to int64_t prints an incorrect value for 32bit ISA RISCV simulation

### ISSUE THREAD

**Issue by lite-david** [srokicki/HybridDBT#6]
In RiscvSimulator::doStep()

`fprintf(stderr,";%lx", (int64_t) REG[i]);
`

While simulating for 32bit ISA, in case of Shift left logical instruction (SLLI) it could print an incorrect value.
For example,` SLLi 400003ff`, 2 prints 10000ffc instead of ffc

**Comment by srokicki** [comment]
Note an issue: this is a 64-bit simulator.
